/*
 * generated by Xtext
 */
package org.xtext.function.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.function.ui.internal.FunctionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FunctionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FunctionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FunctionActivator.getInstance().getInjector(FunctionActivator.ORG_XTEXT_FUNCTION_FUNCTION);
	}
	
}
