/*
* generated by Xtext
*/
package org.xtext.function;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FunctionUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.function.ui.internal.FunctionActivator.getInstance().getInjector("org.xtext.function.Function");
	}
	
}
