/*
* generated by Xtext
*/
package org.xtext.function.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FunctionOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
