/*
 * generated by Xtext
 */
package org.xtext.function.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FunctionUiModule extends org.xtext.function.ui.AbstractFunctionUiModule {
	public FunctionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
