/*
* generated by Xtext
*/

package org.xtext.function.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class FunctionGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsStartParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//
		//	elements+=Start*;
		public ParserRule getRule() { return rule; }

		//elements+=Start*
		public Assignment getElementsAssignment() { return cElementsAssignment; }

		//Start
		public RuleCall getElementsStartParserRuleCall_0() { return cElementsStartParserRuleCall_0; }
	}

	public class StartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Start");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpWithDefinitionsParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final RuleCall cFunctionCallParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Start:
		//
		//	"(" ExpWithDefinitions ")" | FunctionCall;
		public ParserRule getRule() { return rule; }

		//"(" ExpWithDefinitions ")" | FunctionCall
		public Alternatives getAlternatives() { return cAlternatives; }

		//"(" ExpWithDefinitions ")"
		public Group getGroup_0() { return cGroup_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }

		//ExpWithDefinitions
		public RuleCall getExpWithDefinitionsParserRuleCall_0_1() { return cExpWithDefinitionsParserRuleCall_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }

		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_1() { return cFunctionCallParserRuleCall_1; }
	}

	public class ExpWithDefinitionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpWithDefinitions");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExpParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVariableDefinitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFunctionDefinitionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ExpWithDefinitions:
		//
		//	Exp | VariableDefinition | FunctionDefinition;
		public ParserRule getRule() { return rule; }

		//Exp | VariableDefinition | FunctionDefinition
		public Alternatives getAlternatives() { return cAlternatives; }

		//Exp
		public RuleCall getExpParserRuleCall_0() { return cExpParserRuleCall_0; }

		//VariableDefinition
		public RuleCall getVariableDefinitionParserRuleCall_1() { return cVariableDefinitionParserRuleCall_1; }

		//FunctionDefinition
		public RuleCall getFunctionDefinitionParserRuleCall_2() { return cFunctionDefinitionParserRuleCall_2; }
	}

	public class ExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Exp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMathFunctionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Exp:
		//
		//	MathFunction | Expression;
		public ParserRule getRule() { return rule; }

		//=> MathFunction | Expression
		public Alternatives getAlternatives() { return cAlternatives; }

		//=> MathFunction
		public RuleCall getMathFunctionParserRuleCall_0() { return cMathFunctionParserRuleCall_0; }

		//Expression
		public RuleCall getExpressionParserRuleCall_1() { return cExpressionParserRuleCall_1; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cOpAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cOpArithmeticOperationParserRuleCall_0_0_0 = (RuleCall)cOpAssignment_0_0.eContents().get(0);
		private final Assignment cLeftAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cLeftTerminalExpressionParserRuleCall_0_1_0 = (RuleCall)cLeftAssignment_0_1.eContents().get(0);
		private final Assignment cRightAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRightTerminalExpressionParserRuleCall_1_0 = (RuleCall)cRightAssignment_1.eContents().get(0);
		
		//// operacje matematyczne 
		//
		//Expression:
		//
		//	(op=ArithmeticOperation left=TerminalExpression)? right+=TerminalExpression+;
		public ParserRule getRule() { return rule; }

		//(op=ArithmeticOperation left=TerminalExpression)? right+=TerminalExpression+
		public Group getGroup() { return cGroup; }

		//(op=ArithmeticOperation left=TerminalExpression)?
		public Group getGroup_0() { return cGroup_0; }

		//op=ArithmeticOperation
		public Assignment getOpAssignment_0_0() { return cOpAssignment_0_0; }

		//ArithmeticOperation
		public RuleCall getOpArithmeticOperationParserRuleCall_0_0_0() { return cOpArithmeticOperationParserRuleCall_0_0_0; }

		//left=TerminalExpression
		public Assignment getLeftAssignment_0_1() { return cLeftAssignment_0_1; }

		//TerminalExpression
		public RuleCall getLeftTerminalExpressionParserRuleCall_0_1_0() { return cLeftTerminalExpressionParserRuleCall_0_1_0; }

		//right+=TerminalExpression+
		public Assignment getRightAssignment_1() { return cRightAssignment_1; }

		//TerminalExpression
		public RuleCall getRightTerminalExpressionParserRuleCall_1_0() { return cRightTerminalExpressionParserRuleCall_1_0; }
	}

	public class TerminalExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TerminalExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cVariableAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final CrossReference cVariableVariableDefinitionCrossReference_1_0 = (CrossReference)cVariableAssignment_1.eContents().get(0);
		private final RuleCall cVariableVariableDefinitionNAMETerminalRuleCall_1_0_1 = (RuleCall)cVariableVariableDefinitionCrossReference_1_0.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cValueDOUBLETerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Assignment cFunctioncallAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cFunctioncallFunctionCallParserRuleCall_3_0 = (RuleCall)cFunctioncallAssignment_3.eContents().get(0);
		
		//TerminalExpression:
		//
		//	"(" Exp ")" | variable=[VariableDefinition|NAME] | value=DOUBLE | functioncall=FunctionCall;
		public ParserRule getRule() { return rule; }

		//"(" Exp ")" | variable=[VariableDefinition|NAME] | value=DOUBLE | functioncall=FunctionCall
		public Alternatives getAlternatives() { return cAlternatives; }

		//"(" Exp ")"
		public Group getGroup_0() { return cGroup_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }

		//Exp
		public RuleCall getExpParserRuleCall_0_1() { return cExpParserRuleCall_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }

		//variable=[VariableDefinition|NAME]
		public Assignment getVariableAssignment_1() { return cVariableAssignment_1; }

		//[VariableDefinition|NAME]
		public CrossReference getVariableVariableDefinitionCrossReference_1_0() { return cVariableVariableDefinitionCrossReference_1_0; }

		//NAME
		public RuleCall getVariableVariableDefinitionNAMETerminalRuleCall_1_0_1() { return cVariableVariableDefinitionNAMETerminalRuleCall_1_0_1; }

		//value=DOUBLE
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//DOUBLE
		public RuleCall getValueDOUBLETerminalRuleCall_2_0() { return cValueDOUBLETerminalRuleCall_2_0; }

		//functioncall=FunctionCall
		public Assignment getFunctioncallAssignment_3() { return cFunctioncallAssignment_3; }

		//FunctionCall
		public RuleCall getFunctioncallFunctionCallParserRuleCall_3_0() { return cFunctioncallFunctionCallParserRuleCall_3_0; }
	}

	public class ArithmeticOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ArithmeticOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cSolidusKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cAsteriskKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//ArithmeticOperation:
		//
		//	"+" | "-" | "/" | "*";
		public ParserRule getRule() { return rule; }

		//"+" | "-" | "/" | "*"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"+"
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }

		//"-"
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }

		//"/"
		public Keyword getSolidusKeyword_2() { return cSolidusKeyword_2; }

		//"*"
		public Keyword getAsteriskKeyword_3() { return cAsteriskKeyword_3; }
	}

	public class MathFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MathFunction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMathTwoArgParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMathOneArgParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// funkcje matematyczne
		//
		//MathFunction:
		//
		//	MathTwoArg | MathOneArg;
		public ParserRule getRule() { return rule; }

		//MathTwoArg | MathOneArg
		public Alternatives getAlternatives() { return cAlternatives; }

		//MathTwoArg
		public RuleCall getMathTwoArgParserRuleCall_0() { return cMathTwoArgParserRuleCall_0; }

		//MathOneArg
		public RuleCall getMathOneArgParserRuleCall_1() { return cMathOneArgParserRuleCall_1; }
	}

	public class MathTwoArgElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MathTwoArg");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cFunctionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cFunctionTwoArgFunctionParserRuleCall_0_0_0 = (RuleCall)cFunctionAssignment_0_0.eContents().get(0);
		private final Assignment cLeftAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cLeftTerminalExpressionParserRuleCall_0_1_0 = (RuleCall)cLeftAssignment_0_1.eContents().get(0);
		private final Assignment cRightAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRightTerminalExpressionParserRuleCall_1_0 = (RuleCall)cRightAssignment_1.eContents().get(0);
		
		//MathTwoArg:
		//
		//	(function=TwoArgFunction left=TerminalExpression)? right=TerminalExpression;
		public ParserRule getRule() { return rule; }

		//(function=TwoArgFunction left=TerminalExpression)? right=TerminalExpression
		public Group getGroup() { return cGroup; }

		//(function=TwoArgFunction left=TerminalExpression)?
		public Group getGroup_0() { return cGroup_0; }

		//function=TwoArgFunction
		public Assignment getFunctionAssignment_0_0() { return cFunctionAssignment_0_0; }

		//TwoArgFunction
		public RuleCall getFunctionTwoArgFunctionParserRuleCall_0_0_0() { return cFunctionTwoArgFunctionParserRuleCall_0_0_0; }

		//left=TerminalExpression
		public Assignment getLeftAssignment_0_1() { return cLeftAssignment_0_1; }

		//TerminalExpression
		public RuleCall getLeftTerminalExpressionParserRuleCall_0_1_0() { return cLeftTerminalExpressionParserRuleCall_0_1_0; }

		//right=TerminalExpression
		public Assignment getRightAssignment_1() { return cRightAssignment_1; }

		//TerminalExpression
		public RuleCall getRightTerminalExpressionParserRuleCall_1_0() { return cRightTerminalExpressionParserRuleCall_1_0; }
	}

	public class MathOneArgElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MathOneArg");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFunctionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFunctionOneArgFunctionParserRuleCall_0_0 = (RuleCall)cFunctionAssignment_0.eContents().get(0);
		private final Assignment cLeftAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLeftTerminalExpressionParserRuleCall_1_0 = (RuleCall)cLeftAssignment_1.eContents().get(0);
		
		//MathOneArg:
		//
		//	function=OneArgFunction left=TerminalExpression;
		public ParserRule getRule() { return rule; }

		//function=OneArgFunction left=TerminalExpression
		public Group getGroup() { return cGroup; }

		//function=OneArgFunction
		public Assignment getFunctionAssignment_0() { return cFunctionAssignment_0; }

		//OneArgFunction
		public RuleCall getFunctionOneArgFunctionParserRuleCall_0_0() { return cFunctionOneArgFunctionParserRuleCall_0_0; }

		//left=TerminalExpression
		public Assignment getLeftAssignment_1() { return cLeftAssignment_1; }

		//TerminalExpression
		public RuleCall getLeftTerminalExpressionParserRuleCall_1_0() { return cLeftTerminalExpressionParserRuleCall_1_0; }
	}

	public class TwoArgFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TwoArgFunction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cMaxKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cMinKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cPowKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//TwoArgFunction:
		//
		//	"max" | "min" | "pow";
		public ParserRule getRule() { return rule; }

		//"max" | "min" | "pow"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"max"
		public Keyword getMaxKeyword_0() { return cMaxKeyword_0; }

		//"min"
		public Keyword getMinKeyword_1() { return cMinKeyword_1; }

		//"pow"
		public Keyword getPowKeyword_2() { return cPowKeyword_2; }
	}

	public class OneArgFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OneArgFunction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cSqrtKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLogKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//OneArgFunction:
		//
		//	"sqrt" | "log";
		public ParserRule getRule() { return rule; }

		//"sqrt" | "log"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"sqrt"
		public Keyword getSqrtKeyword_0() { return cSqrtKeyword_0; }

		//"log"
		public Keyword getLogKeyword_1() { return cLogKeyword_1; }
	}

	public class VariableDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDefineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumberDOUBLETerminalRuleCall_2_0 = (RuleCall)cNumberAssignment_2.eContents().get(0);
		
		//VariableDefinition:
		//
		//	"define" name=NAME number=DOUBLE;
		public ParserRule getRule() { return rule; }

		//"define" name=NAME number=DOUBLE
		public Group getGroup() { return cGroup; }

		//"define"
		public Keyword getDefineKeyword_0() { return cDefineKeyword_0; }

		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }

		//number=DOUBLE
		public Assignment getNumberAssignment_2() { return cNumberAssignment_2; }

		//DOUBLE
		public RuleCall getNumberDOUBLETerminalRuleCall_2_0() { return cNumberDOUBLETerminalRuleCall_2_0; }
	}

	public class FunctionDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDefineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cParametersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParametersParameterParserRuleCall_3_0 = (RuleCall)cParametersAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExpAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExpExpInFunParserRuleCall_6_0 = (RuleCall)cExpAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//FunctionDefinition:
		//
		//	"define" "(" name=NAME parameters+=Parameter+ ")" "(" exp=ExpInFun ")";
		public ParserRule getRule() { return rule; }

		//"define" "(" name=NAME parameters+=Parameter+ ")" "(" exp=ExpInFun ")"
		public Group getGroup() { return cGroup; }

		//"define"
		public Keyword getDefineKeyword_0() { return cDefineKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }

		//parameters+=Parameter+
		public Assignment getParametersAssignment_3() { return cParametersAssignment_3; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_3_0() { return cParametersParameterParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }

		//"("
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }

		//exp=ExpInFun
		public Assignment getExpAssignment_6() { return cExpAssignment_6; }

		//ExpInFun
		public RuleCall getExpExpInFunParserRuleCall_6_0() { return cExpExpInFunParserRuleCall_6_0; }

		//")"
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNamePARAMNAMETerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Parameter:
		//
		//	name=PARAMNAME;
		public ParserRule getRule() { return rule; }

		//name=PARAMNAME
		public Assignment getNameAssignment() { return cNameAssignment; }

		//PARAMNAME
		public RuleCall getNamePARAMNAMETerminalRuleCall_0() { return cNamePARAMNAMETerminalRuleCall_0; }
	}

	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCallKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFuncAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cFuncFunctionDefinitionCrossReference_2_0 = (CrossReference)cFuncAssignment_2.eContents().get(0);
		private final RuleCall cFuncFunctionDefinitionNAMETerminalRuleCall_2_0_1 = (RuleCall)cFuncFunctionDefinitionCrossReference_2_0.eContents().get(1);
		private final Assignment cParamvaluesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParamvaluesParamValuesParserRuleCall_3_0 = (RuleCall)cParamvaluesAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FunctionCall:
		//
		//	"(" "call" func=[FunctionDefinition|NAME] paramvalues+=ParamValues* ")";
		public ParserRule getRule() { return rule; }

		//"(" "call" func=[FunctionDefinition|NAME] paramvalues+=ParamValues* ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//"call"
		public Keyword getCallKeyword_1() { return cCallKeyword_1; }

		//func=[FunctionDefinition|NAME]
		public Assignment getFuncAssignment_2() { return cFuncAssignment_2; }

		//[FunctionDefinition|NAME]
		public CrossReference getFuncFunctionDefinitionCrossReference_2_0() { return cFuncFunctionDefinitionCrossReference_2_0; }

		//NAME
		public RuleCall getFuncFunctionDefinitionNAMETerminalRuleCall_2_0_1() { return cFuncFunctionDefinitionNAMETerminalRuleCall_2_0_1; }

		//paramvalues+=ParamValues*
		public Assignment getParamvaluesAssignment_3() { return cParamvaluesAssignment_3; }

		//ParamValues
		public RuleCall getParamvaluesParamValuesParserRuleCall_3_0() { return cParamvaluesParamValuesParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class ParamValuesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParamValues");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValueDOUBLETerminalRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Assignment cVariableAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final CrossReference cVariableVariableDefinitionCrossReference_1_0 = (CrossReference)cVariableAssignment_1.eContents().get(0);
		private final RuleCall cVariableVariableDefinitionNAMETerminalRuleCall_1_0_1 = (RuleCall)cVariableVariableDefinitionCrossReference_1_0.eContents().get(1);
		
		//ParamValues:
		//
		//	value=DOUBLE | variable=[VariableDefinition|NAME];
		public ParserRule getRule() { return rule; }

		//value=DOUBLE | variable=[VariableDefinition|NAME]
		public Alternatives getAlternatives() { return cAlternatives; }

		//value=DOUBLE
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//DOUBLE
		public RuleCall getValueDOUBLETerminalRuleCall_0_0() { return cValueDOUBLETerminalRuleCall_0_0; }

		//variable=[VariableDefinition|NAME]
		public Assignment getVariableAssignment_1() { return cVariableAssignment_1; }

		//[VariableDefinition|NAME]
		public CrossReference getVariableVariableDefinitionCrossReference_1_0() { return cVariableVariableDefinitionCrossReference_1_0; }

		//NAME
		public RuleCall getVariableVariableDefinitionNAMETerminalRuleCall_1_0_1() { return cVariableVariableDefinitionNAMETerminalRuleCall_1_0_1; }
	}

	public class ExpInFunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpInFun");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMathFunctionInFunParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExpressionInFunParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// -- elementy ciala funkcji
		//
		//ExpInFun:
		//
		//	MathFunctionInFun | ExpressionInFun;
		public ParserRule getRule() { return rule; }

		//=> MathFunctionInFun | ExpressionInFun
		public Alternatives getAlternatives() { return cAlternatives; }

		//=> MathFunctionInFun
		public RuleCall getMathFunctionInFunParserRuleCall_0() { return cMathFunctionInFunParserRuleCall_0; }

		//ExpressionInFun
		public RuleCall getExpressionInFunParserRuleCall_1() { return cExpressionInFunParserRuleCall_1; }
	}

	public class ExpressionInFunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpressionInFun");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cOpAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cOpArithmeticOperationParserRuleCall_0_0_0 = (RuleCall)cOpAssignment_0_0.eContents().get(0);
		private final Assignment cLeftAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cLeftTerminalExpressionInFunParserRuleCall_0_1_0 = (RuleCall)cLeftAssignment_0_1.eContents().get(0);
		private final Assignment cRightAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRightTerminalExpressionInFunParserRuleCall_1_0 = (RuleCall)cRightAssignment_1.eContents().get(0);
		
		//ExpressionInFun:
		//
		//	(op=ArithmeticOperation left=TerminalExpressionInFun)? right+=TerminalExpressionInFun+;
		public ParserRule getRule() { return rule; }

		//(op=ArithmeticOperation left=TerminalExpressionInFun)? right+=TerminalExpressionInFun+
		public Group getGroup() { return cGroup; }

		//(op=ArithmeticOperation left=TerminalExpressionInFun)?
		public Group getGroup_0() { return cGroup_0; }

		//op=ArithmeticOperation
		public Assignment getOpAssignment_0_0() { return cOpAssignment_0_0; }

		//ArithmeticOperation
		public RuleCall getOpArithmeticOperationParserRuleCall_0_0_0() { return cOpArithmeticOperationParserRuleCall_0_0_0; }

		//left=TerminalExpressionInFun
		public Assignment getLeftAssignment_0_1() { return cLeftAssignment_0_1; }

		//TerminalExpressionInFun
		public RuleCall getLeftTerminalExpressionInFunParserRuleCall_0_1_0() { return cLeftTerminalExpressionInFunParserRuleCall_0_1_0; }

		//right+=TerminalExpressionInFun+
		public Assignment getRightAssignment_1() { return cRightAssignment_1; }

		//TerminalExpressionInFun
		public RuleCall getRightTerminalExpressionInFunParserRuleCall_1_0() { return cRightTerminalExpressionInFunParserRuleCall_1_0; }
	}

	public class TerminalExpressionInFunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TerminalExpressionInFun");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpInFunParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cValueDOUBLETerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final Assignment cParameterAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final CrossReference cParameterParameterCrossReference_2_0 = (CrossReference)cParameterAssignment_2.eContents().get(0);
		private final RuleCall cParameterParameterPARAMNAMETerminalRuleCall_2_0_1 = (RuleCall)cParameterParameterCrossReference_2_0.eContents().get(1);
		
		//TerminalExpressionInFun:
		//
		//	"(" ExpInFun ")" | value=DOUBLE | parameter=[Parameter|PARAMNAME];
		public ParserRule getRule() { return rule; }

		//"(" ExpInFun ")" | value=DOUBLE | parameter=[Parameter|PARAMNAME]
		public Alternatives getAlternatives() { return cAlternatives; }

		//"(" ExpInFun ")"
		public Group getGroup_0() { return cGroup_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }

		//ExpInFun
		public RuleCall getExpInFunParserRuleCall_0_1() { return cExpInFunParserRuleCall_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }

		//value=DOUBLE
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//DOUBLE
		public RuleCall getValueDOUBLETerminalRuleCall_1_0() { return cValueDOUBLETerminalRuleCall_1_0; }

		//parameter=[Parameter|PARAMNAME]
		public Assignment getParameterAssignment_2() { return cParameterAssignment_2; }

		//[Parameter|PARAMNAME]
		public CrossReference getParameterParameterCrossReference_2_0() { return cParameterParameterCrossReference_2_0; }

		//PARAMNAME
		public RuleCall getParameterParameterPARAMNAMETerminalRuleCall_2_0_1() { return cParameterParameterPARAMNAMETerminalRuleCall_2_0_1; }
	}

	public class MathFunctionInFunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MathFunctionInFun");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMathTwoArgInFunParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMathOneArgInFunParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//MathFunctionInFun:
		//
		//	MathTwoArgInFun | MathOneArgInFun;
		public ParserRule getRule() { return rule; }

		//MathTwoArgInFun | MathOneArgInFun
		public Alternatives getAlternatives() { return cAlternatives; }

		//MathTwoArgInFun
		public RuleCall getMathTwoArgInFunParserRuleCall_0() { return cMathTwoArgInFunParserRuleCall_0; }

		//MathOneArgInFun
		public RuleCall getMathOneArgInFunParserRuleCall_1() { return cMathOneArgInFunParserRuleCall_1; }
	}

	public class MathTwoArgInFunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MathTwoArgInFun");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cFunctionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cFunctionTwoArgFunctionParserRuleCall_0_0_0 = (RuleCall)cFunctionAssignment_0_0.eContents().get(0);
		private final Assignment cLeftAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cLeftTerminalExpressionInFunParserRuleCall_0_1_0 = (RuleCall)cLeftAssignment_0_1.eContents().get(0);
		private final Assignment cRightAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRightTerminalExpressionInFunParserRuleCall_1_0 = (RuleCall)cRightAssignment_1.eContents().get(0);
		
		//MathTwoArgInFun:
		//
		//	(function=TwoArgFunction left=TerminalExpressionInFun)? right=TerminalExpressionInFun;
		public ParserRule getRule() { return rule; }

		//(function=TwoArgFunction left=TerminalExpressionInFun)? right=TerminalExpressionInFun
		public Group getGroup() { return cGroup; }

		//(function=TwoArgFunction left=TerminalExpressionInFun)?
		public Group getGroup_0() { return cGroup_0; }

		//function=TwoArgFunction
		public Assignment getFunctionAssignment_0_0() { return cFunctionAssignment_0_0; }

		//TwoArgFunction
		public RuleCall getFunctionTwoArgFunctionParserRuleCall_0_0_0() { return cFunctionTwoArgFunctionParserRuleCall_0_0_0; }

		//left=TerminalExpressionInFun
		public Assignment getLeftAssignment_0_1() { return cLeftAssignment_0_1; }

		//TerminalExpressionInFun
		public RuleCall getLeftTerminalExpressionInFunParserRuleCall_0_1_0() { return cLeftTerminalExpressionInFunParserRuleCall_0_1_0; }

		//right=TerminalExpressionInFun
		public Assignment getRightAssignment_1() { return cRightAssignment_1; }

		//TerminalExpressionInFun
		public RuleCall getRightTerminalExpressionInFunParserRuleCall_1_0() { return cRightTerminalExpressionInFunParserRuleCall_1_0; }
	}

	public class MathOneArgInFunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MathOneArgInFun");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFunctionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFunctionOneArgFunctionParserRuleCall_0_0 = (RuleCall)cFunctionAssignment_0.eContents().get(0);
		private final Assignment cLeftAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLeftTerminalExpressionInFunParserRuleCall_1_0 = (RuleCall)cLeftAssignment_1.eContents().get(0);
		
		//MathOneArgInFun:
		//
		//	function=OneArgFunction left=TerminalExpressionInFun;
		public ParserRule getRule() { return rule; }

		//function=OneArgFunction left=TerminalExpressionInFun
		public Group getGroup() { return cGroup; }

		//function=OneArgFunction
		public Assignment getFunctionAssignment_0() { return cFunctionAssignment_0; }

		//OneArgFunction
		public RuleCall getFunctionOneArgFunctionParserRuleCall_0_0() { return cFunctionOneArgFunctionParserRuleCall_0_0; }

		//left=TerminalExpressionInFun
		public Assignment getLeftAssignment_1() { return cLeftAssignment_1; }

		//TerminalExpressionInFun
		public RuleCall getLeftTerminalExpressionInFunParserRuleCall_1_0() { return cLeftTerminalExpressionInFunParserRuleCall_1_0; }
	}

	public class IfStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IfStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cIfKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIftypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIftypeIfTypeParserRuleCall_3_0 = (RuleCall)cIftypeAssignment_3.eContents().get(0);
		private final Assignment cLeftAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLeftExpParserRuleCall_4_0 = (RuleCall)cLeftAssignment_4.eContents().get(0);
		private final Assignment cRightAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRightExpParserRuleCall_5_0 = (RuleCall)cRightAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cWhentrueAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cWhentrueExpParserRuleCall_7_0 = (RuleCall)cWhentrueAssignment_7.eContents().get(0);
		private final Assignment cWhenfalseAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cWhenfalseExpParserRuleCall_8_0 = (RuleCall)cWhenfalseAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//// instrukcja warunkowa
		//
		//IfStatement:
		//
		//	"(" "if" "(" iftype=IfType left=Exp right=Exp ")" whentrue=Exp whenfalse=Exp ")";
		public ParserRule getRule() { return rule; }

		//"(" "if" "(" iftype=IfType left=Exp right=Exp ")" whentrue=Exp whenfalse=Exp ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//"if"
		public Keyword getIfKeyword_1() { return cIfKeyword_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//iftype=IfType
		public Assignment getIftypeAssignment_3() { return cIftypeAssignment_3; }

		//IfType
		public RuleCall getIftypeIfTypeParserRuleCall_3_0() { return cIftypeIfTypeParserRuleCall_3_0; }

		//left=Exp
		public Assignment getLeftAssignment_4() { return cLeftAssignment_4; }

		//Exp
		public RuleCall getLeftExpParserRuleCall_4_0() { return cLeftExpParserRuleCall_4_0; }

		//right=Exp
		public Assignment getRightAssignment_5() { return cRightAssignment_5; }

		//Exp
		public RuleCall getRightExpParserRuleCall_5_0() { return cRightExpParserRuleCall_5_0; }

		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }

		//whentrue=Exp
		public Assignment getWhentrueAssignment_7() { return cWhentrueAssignment_7; }

		//Exp
		public RuleCall getWhentrueExpParserRuleCall_7_0() { return cWhentrueExpParserRuleCall_7_0; }

		//whenfalse=Exp
		public Assignment getWhenfalseAssignment_8() { return cWhenfalseAssignment_8; }

		//Exp
		public RuleCall getWhenfalseExpParserRuleCall_8_0() { return cWhenfalseExpParserRuleCall_8_0; }

		//")"
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}

	public class IfTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IfType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cEqualKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLessKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cGreaterKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//IfType:
		//
		//	"equal" | "less" | "greater";
		public ParserRule getRule() { return rule; }

		//"equal" | "less" | "greater"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"equal"
		public Keyword getEqualKeyword_0() { return cEqualKeyword_0; }

		//"less"
		public Keyword getLessKeyword_1() { return cLessKeyword_1; }

		//"greater"
		public Keyword getGreaterKeyword_2() { return cGreaterKeyword_2; }
	}
	
	
	private ModelElements pModel;
	private StartElements pStart;
	private ExpWithDefinitionsElements pExpWithDefinitions;
	private ExpElements pExp;
	private ExpressionElements pExpression;
	private TerminalExpressionElements pTerminalExpression;
	private ArithmeticOperationElements pArithmeticOperation;
	private MathFunctionElements pMathFunction;
	private MathTwoArgElements pMathTwoArg;
	private MathOneArgElements pMathOneArg;
	private TwoArgFunctionElements pTwoArgFunction;
	private OneArgFunctionElements pOneArgFunction;
	private VariableDefinitionElements pVariableDefinition;
	private FunctionDefinitionElements pFunctionDefinition;
	private ParameterElements pParameter;
	private FunctionCallElements pFunctionCall;
	private ParamValuesElements pParamValues;
	private ExpInFunElements pExpInFun;
	private ExpressionInFunElements pExpressionInFun;
	private TerminalExpressionInFunElements pTerminalExpressionInFun;
	private MathFunctionInFunElements pMathFunctionInFun;
	private MathTwoArgInFunElements pMathTwoArgInFun;
	private MathOneArgInFunElements pMathOneArgInFun;
	private IfStatementElements pIfStatement;
	private IfTypeElements pIfType;
	private TerminalRule tDOUBLE;
	private TerminalRule tNAME;
	private TerminalRule tPARAMNAME;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public FunctionGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.function.Function".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	//Model:
	//
	//	elements+=Start*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Start:
	//
	//	"(" ExpWithDefinitions ")" | FunctionCall;
	public StartElements getStartAccess() {
		return (pStart != null) ? pStart : (pStart = new StartElements());
	}
	
	public ParserRule getStartRule() {
		return getStartAccess().getRule();
	}

	//ExpWithDefinitions:
	//
	//	Exp | VariableDefinition | FunctionDefinition;
	public ExpWithDefinitionsElements getExpWithDefinitionsAccess() {
		return (pExpWithDefinitions != null) ? pExpWithDefinitions : (pExpWithDefinitions = new ExpWithDefinitionsElements());
	}
	
	public ParserRule getExpWithDefinitionsRule() {
		return getExpWithDefinitionsAccess().getRule();
	}

	//Exp:
	//
	//	MathFunction | Expression;
	public ExpElements getExpAccess() {
		return (pExp != null) ? pExp : (pExp = new ExpElements());
	}
	
	public ParserRule getExpRule() {
		return getExpAccess().getRule();
	}

	//// operacje matematyczne 
	//
	//Expression:
	//
	//	(op=ArithmeticOperation left=TerminalExpression)? right+=TerminalExpression+;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//TerminalExpression:
	//
	//	"(" Exp ")" | variable=[VariableDefinition|NAME] | value=DOUBLE | functioncall=FunctionCall;
	public TerminalExpressionElements getTerminalExpressionAccess() {
		return (pTerminalExpression != null) ? pTerminalExpression : (pTerminalExpression = new TerminalExpressionElements());
	}
	
	public ParserRule getTerminalExpressionRule() {
		return getTerminalExpressionAccess().getRule();
	}

	//ArithmeticOperation:
	//
	//	"+" | "-" | "/" | "*";
	public ArithmeticOperationElements getArithmeticOperationAccess() {
		return (pArithmeticOperation != null) ? pArithmeticOperation : (pArithmeticOperation = new ArithmeticOperationElements());
	}
	
	public ParserRule getArithmeticOperationRule() {
		return getArithmeticOperationAccess().getRule();
	}

	//// funkcje matematyczne
	//
	//MathFunction:
	//
	//	MathTwoArg | MathOneArg;
	public MathFunctionElements getMathFunctionAccess() {
		return (pMathFunction != null) ? pMathFunction : (pMathFunction = new MathFunctionElements());
	}
	
	public ParserRule getMathFunctionRule() {
		return getMathFunctionAccess().getRule();
	}

	//MathTwoArg:
	//
	//	(function=TwoArgFunction left=TerminalExpression)? right=TerminalExpression;
	public MathTwoArgElements getMathTwoArgAccess() {
		return (pMathTwoArg != null) ? pMathTwoArg : (pMathTwoArg = new MathTwoArgElements());
	}
	
	public ParserRule getMathTwoArgRule() {
		return getMathTwoArgAccess().getRule();
	}

	//MathOneArg:
	//
	//	function=OneArgFunction left=TerminalExpression;
	public MathOneArgElements getMathOneArgAccess() {
		return (pMathOneArg != null) ? pMathOneArg : (pMathOneArg = new MathOneArgElements());
	}
	
	public ParserRule getMathOneArgRule() {
		return getMathOneArgAccess().getRule();
	}

	//TwoArgFunction:
	//
	//	"max" | "min" | "pow";
	public TwoArgFunctionElements getTwoArgFunctionAccess() {
		return (pTwoArgFunction != null) ? pTwoArgFunction : (pTwoArgFunction = new TwoArgFunctionElements());
	}
	
	public ParserRule getTwoArgFunctionRule() {
		return getTwoArgFunctionAccess().getRule();
	}

	//OneArgFunction:
	//
	//	"sqrt" | "log";
	public OneArgFunctionElements getOneArgFunctionAccess() {
		return (pOneArgFunction != null) ? pOneArgFunction : (pOneArgFunction = new OneArgFunctionElements());
	}
	
	public ParserRule getOneArgFunctionRule() {
		return getOneArgFunctionAccess().getRule();
	}

	//VariableDefinition:
	//
	//	"define" name=NAME number=DOUBLE;
	public VariableDefinitionElements getVariableDefinitionAccess() {
		return (pVariableDefinition != null) ? pVariableDefinition : (pVariableDefinition = new VariableDefinitionElements());
	}
	
	public ParserRule getVariableDefinitionRule() {
		return getVariableDefinitionAccess().getRule();
	}

	//FunctionDefinition:
	//
	//	"define" "(" name=NAME parameters+=Parameter+ ")" "(" exp=ExpInFun ")";
	public FunctionDefinitionElements getFunctionDefinitionAccess() {
		return (pFunctionDefinition != null) ? pFunctionDefinition : (pFunctionDefinition = new FunctionDefinitionElements());
	}
	
	public ParserRule getFunctionDefinitionRule() {
		return getFunctionDefinitionAccess().getRule();
	}

	//Parameter:
	//
	//	name=PARAMNAME;
	public ParameterElements getParameterAccess() {
		return (pParameter != null) ? pParameter : (pParameter = new ParameterElements());
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//FunctionCall:
	//
	//	"(" "call" func=[FunctionDefinition|NAME] paramvalues+=ParamValues* ")";
	public FunctionCallElements getFunctionCallAccess() {
		return (pFunctionCall != null) ? pFunctionCall : (pFunctionCall = new FunctionCallElements());
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}

	//ParamValues:
	//
	//	value=DOUBLE | variable=[VariableDefinition|NAME];
	public ParamValuesElements getParamValuesAccess() {
		return (pParamValues != null) ? pParamValues : (pParamValues = new ParamValuesElements());
	}
	
	public ParserRule getParamValuesRule() {
		return getParamValuesAccess().getRule();
	}

	//// -- elementy ciala funkcji
	//
	//ExpInFun:
	//
	//	MathFunctionInFun | ExpressionInFun;
	public ExpInFunElements getExpInFunAccess() {
		return (pExpInFun != null) ? pExpInFun : (pExpInFun = new ExpInFunElements());
	}
	
	public ParserRule getExpInFunRule() {
		return getExpInFunAccess().getRule();
	}

	//ExpressionInFun:
	//
	//	(op=ArithmeticOperation left=TerminalExpressionInFun)? right+=TerminalExpressionInFun+;
	public ExpressionInFunElements getExpressionInFunAccess() {
		return (pExpressionInFun != null) ? pExpressionInFun : (pExpressionInFun = new ExpressionInFunElements());
	}
	
	public ParserRule getExpressionInFunRule() {
		return getExpressionInFunAccess().getRule();
	}

	//TerminalExpressionInFun:
	//
	//	"(" ExpInFun ")" | value=DOUBLE | parameter=[Parameter|PARAMNAME];
	public TerminalExpressionInFunElements getTerminalExpressionInFunAccess() {
		return (pTerminalExpressionInFun != null) ? pTerminalExpressionInFun : (pTerminalExpressionInFun = new TerminalExpressionInFunElements());
	}
	
	public ParserRule getTerminalExpressionInFunRule() {
		return getTerminalExpressionInFunAccess().getRule();
	}

	//MathFunctionInFun:
	//
	//	MathTwoArgInFun | MathOneArgInFun;
	public MathFunctionInFunElements getMathFunctionInFunAccess() {
		return (pMathFunctionInFun != null) ? pMathFunctionInFun : (pMathFunctionInFun = new MathFunctionInFunElements());
	}
	
	public ParserRule getMathFunctionInFunRule() {
		return getMathFunctionInFunAccess().getRule();
	}

	//MathTwoArgInFun:
	//
	//	(function=TwoArgFunction left=TerminalExpressionInFun)? right=TerminalExpressionInFun;
	public MathTwoArgInFunElements getMathTwoArgInFunAccess() {
		return (pMathTwoArgInFun != null) ? pMathTwoArgInFun : (pMathTwoArgInFun = new MathTwoArgInFunElements());
	}
	
	public ParserRule getMathTwoArgInFunRule() {
		return getMathTwoArgInFunAccess().getRule();
	}

	//MathOneArgInFun:
	//
	//	function=OneArgFunction left=TerminalExpressionInFun;
	public MathOneArgInFunElements getMathOneArgInFunAccess() {
		return (pMathOneArgInFun != null) ? pMathOneArgInFun : (pMathOneArgInFun = new MathOneArgInFunElements());
	}
	
	public ParserRule getMathOneArgInFunRule() {
		return getMathOneArgInFunAccess().getRule();
	}

	//// instrukcja warunkowa
	//
	//IfStatement:
	//
	//	"(" "if" "(" iftype=IfType left=Exp right=Exp ")" whentrue=Exp whenfalse=Exp ")";
	public IfStatementElements getIfStatementAccess() {
		return (pIfStatement != null) ? pIfStatement : (pIfStatement = new IfStatementElements());
	}
	
	public ParserRule getIfStatementRule() {
		return getIfStatementAccess().getRule();
	}

	//IfType:
	//
	//	"equal" | "less" | "greater";
	public IfTypeElements getIfTypeAccess() {
		return (pIfType != null) ? pIfType : (pIfType = new IfTypeElements());
	}
	
	public ParserRule getIfTypeRule() {
		return getIfTypeAccess().getRule();
	}

	//terminal DOUBLE:
	//
	//	"0".."9"+ "." "0".."9"+;
	public TerminalRule getDOUBLERule() {
		return (tDOUBLE != null) ? tDOUBLE : (tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DOUBLE"));
	} 

	//terminal NAME:
	//
	//	("a".."z" | "A".."Z")*;
	public TerminalRule getNAMERule() {
		return (tNAME != null) ? tNAME : (tNAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NAME"));
	} 

	/// * 
	//
	//	
	//
	//Element:
	//
	//	Expression | Num
	//
	//;
	//
	//
	//
	//Num:
	//
	//	value=INT
	//
	//;
	//
	//	
	//
	//Expression:
	//
	//	'(' Operation  ')';
	//
	//	
	//
	//Operation:
	//
	//	 op=XAdditiveExpression left=Element right=Element 
	//
	//;
	//
	//
	//
	//Function:
	//
	//	'define' Designation 	
	//
	//;
	//
	//
	//
	//Designation:
	//
	//	Name | Variable
	//
	//;
	//
	//Name:
	//
	//	'(' name=STRING arg=Element ')'
	//
	//;
	//
	//Variable:
	//
	//	name=STRING
	//
	//;
	//
	//
	//
	// * / terminal PARAMNAME:
	//
	//	"_" ("a".."z" | "A".."Z") ("a".."z" | "A".."Z")*;
	public TerminalRule getPARAMNAMERule() {
		return (tPARAMNAME != null) ? tPARAMNAME : (tPARAMNAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PARAMNAME"));
	} 

	//XExpression:
	//
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//
	//	{XAssignment} / * (declaringType=[types::JvmDeclaredType] '::')? * / feature=[types::JvmIdentifiableElement|ValidID]
	//
	//	OpSingleAssign value=XAssignment | XOrExpression (=> ({XBinaryOperation.leftOperand=current}
	//
	//	feature=[types::JvmIdentifiableElement|OpMultiAssign]) rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//
	//	"+=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//
	//	"==" | "!=";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//
	//	"->" | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XCastedExpression | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} "." feature=[types::JvmIdentifiableElement|ValidID]
	//
	//	OpSingleAssign) value=XAssignment | => ({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." |
	//
	//	spreading?="*.")) ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//
	//	feature=[types::JvmIdentifiableElement|ValidID] (=> explicitOperationCall?="(" (memberCallArguments+=XShortClosure |
	//
	//	memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")? memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression |
	//
	//	XForLoopExpression | XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression |
	//
	//	XTryCatchFinallyExpression | XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//
	//	XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaXbase.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//
	//	{XFeatureCall} declaringType=[types::JvmDeclaredType|StaticQualifier]? ("<" typeArguments+=JvmArgumentTypeReference
	//
	//	("," typeArguments+=JvmArgumentTypeReference)* ">")? feature=[types::JvmIdentifiableElement|IdOrSuper] (=>
	//
	//	explicitOperationCall?="(" (featureCallArguments+=XShortClosure | featureCallArguments+=XExpression (","
	//
	//	featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//IdOrSuper:
	//
	//	ValidID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//// This is a workaround since ANTLR will not be able to resolve
	//
	//
	//// StaticQualifier: ValidID ('::' ValidID)*; and XFeatureCall: (StaticQualifier '::')? ValidID
	//
	//
	//// Make sure to change the value converter if you change the syntax of the StaticQualifier
	// StaticQualifier:
	//
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//terminal HEX:
	//
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} "[" "]")* | XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//XFunctionTypeRef:
	//
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//ValidID:
	//
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
