/*
* generated by Xtext
*/
package org.xtext.function.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.function.services.FunctionGrammarAccess;

public class FunctionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FunctionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.function.parser.antlr.internal.InternalFunctionParser createParser(XtextTokenStream stream) {
		return new org.xtext.function.parser.antlr.internal.InternalFunctionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public FunctionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FunctionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
